### PR TITLE
[IAIF-168]: Basic and JWT authentication implementation draft

### PR DESCRIPTION
**Pull request by kochkr**
This commit may need further work. I would be glad to get your advice about next parts:
- Client id and Client secret for this application are hardcoded in the application like they are in CLI. Perhaps they should be configurable.
- I am not completely sure if I am using HttpClient in a right way.

### CODE REVIEW

**Comment by torsv454** [comment]
Some suggestions: 
1. Move the authentication logic to the com.emc.ia.sdk.support.rest.RestClient class so it works even if the configurer is not used. 
2. Refactor out the code to handle different authentication methods into distinct strategy classes. 
3. Properly handle token expiration (renew token before it has expired). 
4. Make client id and client secret configurable (as you point out).
5. Define a payload class for the response, instead of doing httpClient.post(uri, headers, payload, String.class); and then parsing the string using new JSONObject(response), just create AuthenticationResponse (or similar) and do httpClient.post(uri, headers, payload, AuthenticationResponse.class); 
6. Also make sure the build builds locally first. The build currently fails with the patch due to insufficient test coverage.

**Comment by kochkr** [comment]
I think this work is still in progress but I decided to update this pull request so you can check the current state of my work and maybe discuss the implementation.
1. I implemented your suggestions so now the authentication logic is split into different classes and RestClient is changed accordingly. Please, check if the changes are correct from design perspective
2. I had some problems with understanding of the possible implementation of refreshing logic. Now it is made so that the class checks the token for expiration before each rest call (actually it checks if the time difference is close enough to the configured threshold). But I am not completely sure that it is the right way to go. Maybe asyncronous updates by timer would be better, what do you think?

**Comment by torsv454** [comment]
Looks a lot better. Think we can wrap this if you look into the following comments: 
1. Make a factory method _always_ return an instance and make the decision which factory method to call outside of it. 
2. Validate the arguments in the constructors. E.g. it is possible to pass invalid clientId (e.g. "") to Gateway info. 
3. Do not use System.currentTimeMillis directly, instead use the class provided for it com.emc.ia.sdk.support.datetime.Clock. 
4. The refresh logic of JwtAuthentication is not thread safe but if you move it to an asynch timer it should be ok (use the Clock class). E.g. let the timer refresh the token and always assume a valid token. 
5. Use only milliseconds internally. The conversions like System.currentTimeMillis() / 1000000 are confusing, since / 1000 is a second and divide by 1000000 is a unit of 1000 seconds so 16.7 minutes? Try to name the constant appropriately if you want / need to do unit conversions.

**Comment by kochkr** [comment]
Thank you for suggestions. In the last commit I tried to resolve the problems:
1. Renamed factory methods to express what they actually do: return not the instance of a class but the optional of the instance.
2. Added validation to constructors to check for nulls and empty strings.
3. Used Timer class to asyncronously refresh authentication tokens.

I encountered a problem with testing asyncronous refresh. In order to test the request I had to sleep the thread and it does not seem like a right decision. But from another perspective we should test only that the payload is correct. Please, tell me if it is ok to leave it like that or I should refactor this logic.

**Comment by kochkr** [comment]
I think that the changes are finally finished. I made Clock configurable and used it in tests.

Please, look at the changes and tell me if it is acceptable or not.

**Pull request merged**
