### PR TITLE
This is a contribution for sample ingest showing SIP ingestion in IA.…

### PR DESCRIPTION
**Pull request by Manoranjan1987**
… However, this is not a complete working code because it is either missing few IA relation configuration or some bug with the SIP SDK.

### CODE REVIEW

**Comment by Manoranjan1987** [comment]
Please can you help with the required configurations needed to make Ingest work using the SIP SDK.

**Comment by arcadius** [comment]
:+1:

**Comment by RaySinnema** [comment]
I've added a [third sample](https://github.com/Enterprise-Content-Management/infoarchive-sip-sdk/tree/master/samples/sample-3-ingest) that shows how to use the SIP SDK to ingest a SIP into InfoArchive.

**Comment by arcadius** [comment]
Excellent news @RemonSinnema :+1:

**Pull request closed without merging**
